#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=90
STOP=10

USE_PROCD=1
PROG=/usr/bin/snort
CONFIG=/etc/snort/snort.conf
TMP_CONFIG=/tmp/snort/snort.conf

validate_snort_section() {
        uci_validate_section snort snort "${1}" \
                'config_file1:string' \
                'config_file2:string' \
                'config_file3:string' \
                'config_file4:string' \
                'profile:string'
}

start_service() {
        local config_file1 config_file2 config_file3 config_file4 profile
        validate_snort_section snort || {
                echo "validation failed"
                return 1
        }

	sed -i '/^$/d' /etc/snort/rules/exclude.rules
	sed -i '/^$/d' /etc/snort/rules/local.rules

	sh /etc/snort/rules/exclude_rules.sh /etc/snort/rules/exclude.rules &>/dev/null

        rm -f /etc/snort/profile
        ln -s /etc/snort/profiles/$profile /etc/snort/profile

        mkdir -p /tmp/snort
        mkdir -p /etc/snort

        cat $config_file1 > $CONFIG
        cat $config_file2 >> $CONFIG
        cat $config_file3 >> $CONFIG
        cat $config_file4 >> $CONFIG

        ln -sf $CONFIG $TMP_CONFIG

        procd_open_instance
        snort --daq-dir /usr/lib/daq -QND -c /etc/snort/snort8.conf --create-pid --pid-path /var/run/  -G 0x8 -A fast &
	procd_set_param command $PROG "--daq-dir" "/usr/lib/daq/" "-QND" "-c" "/etc/snort/snort7.conf" "--pid-path" "/var/snort/" "--create-pid" "-G" "0x7" "-A" "fast"

        iptables -I FORWARD -j NFQUEUE --queue-balance 7:8 --queue-cpu-fanout
	ip6tables -I FORWARD -j NFQUEUE --queue-balance 7:8 --queue-cpu-fanout		

	SNORT8=$(pidof snort | cut -d' ' -f1)
	SNORT7=$(pidof snort | cut -d' ' -f2)
	schedtool -a 0 $SNORT7
	schedtool -a 1 $SNORT8
        sleep 3

        procd_set_param $config_file1
        procd_set_param $config_file2
        procd_set_param $config_file3
        procd_set_param $config_file4
        procd_set_param respawn
        procd_close_instance
}

stop_service()
{
        iptables -D FORWARD -j NFQUEUE --queue-balance 7:8 --queue-cpu-fanout
	ip6tables -D FORWARD -j NFQUEUE --queue-balance 7:8 --queue-cpu-fanout	
	SNORT8=$(pidof snort | cut -d' ' -f1)
	service_stop ${PROG}

#	SNORT7=$(pidof snort | cut -d' ' -f2)
	kill -9 $SNORT8
#	kill -9 $SNORT7
}

service_triggers()
{
        procd_add_reload_trigger "snort"
        procd_add_validation validate_snort_section
}
