#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=90
STOP=10

USE_PROCD=1
PROG=/usr/bin/snort
CONFIG=/etc/snort/snort.conf
TMP_CONFIG=/tmp/snort/snort.conf

validate_snort_section() {
        uci_validate_section snort snort "${1}" \
                'config_file1:string' \
                'config_file2:string' \
                'config_file3:string' \
                'config_file4:string' \
                'profile:string'
}

start_service() {
        local config_file1 config_file2 config_file3 config_file4 profile
        validate_snort_section snort || {
                echo "validation failed"
                return 1
        }
	sed -i '/^$/d' /etc/snort/rules/exclude.rules
	sed -i '/^$/d' /etc/snort/rules/local.rules
	sh /etc/snort/rules/exclude_rules.sh /etc/snort/rules/exclude.rules &>/dev/null

        rm -f /etc/snort/profile
        ln -s /etc/snort/profiles/$profile /etc/snort/profile

        mkdir -p /tmp/snort
        mkdir -p /etc/snort

        cat $config_file1 > $CONFIG
        cat $config_file2 >> $CONFIG
        cat $config_file3 >> $CONFIG
        cat $config_file4 >> $CONFIG

        ln -sf $CONFIG $TMP_CONFIG

        procd_open_instance
	ifconfig eth0 up promisc
	ifconfig eth2 up promisc
	procd_set_param command $PROG "-i" "eth0:eth2" "--daq-dir" "/usr/lib/daq/" "-QND" "-c" "/etc/snort/snort_bridge.conf" "--pid-path" "/var/snort/" "--create-pid"

        sleep 3

        procd_set_param $config_file1
        procd_set_param $config_file2
        procd_set_param $config_file3
        procd_set_param $config_file4
        procd_set_param respawn
        procd_close_instance
}

stop_service()
{
	service_stop ${PROG}
}

service_triggers()
{
        procd_add_reload_trigger "snort"
        procd_add_validation validate_snort_section
}
